spring:
   kafka:
      bootstrap-servers: kafka:9092
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
vehicle:
   kafka:
      topic: vehicle-locations
server:
   port: 8083